config/routes.rb
UserAdmin::Application.routes.draw do
  resources :roles
  resources :users
  resource :users do
    collection do
      post 'grid_update'
    end
  end

  root :to => 'users#index'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :role_id, :user_id
  belongs_to :user
  belongs_to :role
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :memberships
  has_many :users, :through => :memberships, :uniq => true

  validates :name, presence: true
  validates :description, presence: true
  validates_uniqueness_of  :name, case_sensitive: false

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :role_names, :user_name, :role_ids
  has_many :memberships 
  has_many :roles, :through => :memberships, :uniq => true

  validates :user_name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_uniqueness_of :user_name, case_sensitive: false
  validates :user_name, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    User.all.each do |user|
      user.update_attributes(:role_names => user.roles.map(&:name).sort.join(","))
    end
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @columns = ['id', 'user_name', 'email', 'first_name', 'last_name', 'role_names']
    @users= User.paginate(
      :page     => params[:page],
      :per_page => params[:rows],
      :order    => order_by_from_params(params),
      :conditions => filter_option(params)
     )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: json_for_jqgrid(@users, @columns) }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @roles = @user.roles
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @roles = Role.all
    @user = User.new

    respond_to do |format|
      format.js # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @roles = Role.all
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @roles = Role.all
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        update_role_names
        format.html { render action: "index" }
        format.js 
        format.json { render json: @user, status: :created, location: @user }
      else
        format.js { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    params[:user][:role_ids] ||= []
    @roles = Role.all
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        update_role_names
        format.js 
        format.json { head :no_content }
      else
        format.js { render "edit", id: @user.id }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def grid_update
    @user = User.find_by_id(params[:id])
    if params[:oper] == "del"
        @user.destroy
    end

    render :json => @user
  end

private

  def update_role_names
    @user.update_attributes(:role_names => @user.roles.map(&:name).sort.join(","))
  end
  
  # TODO: put this in helper
  def filter_option options
    condition = []
    if options[:_search] == "true"
      str = options[:searchString]
      case options[:searchOper]
        when "cn"
          condition = ["#{options[:searchField]} like ?", "%#{str}%"]
        when "eq"
          condition = ["#{options[:searchField]} = ?", "#{str}"]
      end
    end
    condition
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  include JqgridsHelper

  def users_jqgrid

    options = {:on_document_ready => true, :html_tags => false}

    grid = [{
      :url => '/users',
      :datatype => 'json',
      :mtype => 'GET',
      :colNames => ['User ID','User Name', 'Email','First Name','Last Name','Roles'],
      :colModel  => [
        { :name => 'id',        :index => 'id',         :width => 80, :align => 'center', :search => false},
        { :name => 'user_name', :index => 'user_name',  :width => 90,  :align => 'center', :editable => true, :search => true },
        { :name => 'email',     :index => 'email',      :width => 180, :editable => true, :search => true},
        { :name => 'first_name',:index => 'first_name', :width => 120, :editable => true, :search => true },
        { :name => 'last_name', :index => 'last_name',  :width => 120, :editable => true, :search => true },
        { :name => 'roles',     :index => 'role_names', :width => 150,:search => true, :sortable => false }
      ],
      :editurl => '/users/grid_update',
      :pager => '#users_pager',
      :rowNum => 20,
      :rowList => [20, 40, 60],
      :sortname => 'id',
      :sortorder => 'desc',
      :viewrecords => true,
      :caption => 'User Admin',
      :height => 400,
      :rowTotal => -1
    }]

    # See http://www.trirand.com/jqgridwiki/doku.php?id=wiki:navigator
    # ('navGrid','#gridpager',{parameters}, prmEdit, prmAdd, prmDel, prmSearch, prmView)

    pager = [:navGrid, "#users_pager", {:edit => false, :add => false, :search => true, :del => true, :refresh => true},
            {height:280, :closeAfterEdit => true, :closeOnEscape => true, :search => true, :refresh => true},
            {height:280, :closeAfterEdit => true, :closeOnEscape => true, :search => true, :refresh => true},
            {reloadAfterSubmit:false},
            {}]

    jqgrid_api 'users_list', grid, pager, options

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAdmin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= yield :head if content_for?(:head)%>
</head>
<body>

<div id="edit_user" class="modal_popup" title="Edit User" style="display:none"></div>
<div id="add_user" class="modal_popup" title="Add User" style="display:none"></div>
<div id="add_role" class="modal_popup" title="Add/Edit Role" style="display:none"></div>

<div id="main">
<%= yield %>
</div>
</body>
</html>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table id="role_list">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan=2>Action</th>
  </tr>

<% @roles.each do |role| %>
  <tr class="<%= cycle('oddrow','evenrow') %>">
    <td><%= role.name %></td>
    <td><%= role.description%></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Delete', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>Create New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>
<p>
  <b>Description:</b>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_edit.html.erb
<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user, remote: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
   <div> 
   <%= f.label :roles %><br />
  <% @roles.each do |role| %>
    <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role), {:id => "user_role_ids_#{role.id}"} %>
    <%= role.name%>
  <% end %>
   </div> 
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br />

app/views/users/_new.html.erb
<%= render 'form' %>

app/views/users/create.js.erb
$('#add_user').dialog('close');
$('#users_list').trigger('reloadGrid');

app/views/users/edit.js.erb
$('#edit_user').html ("<%= escape_javascript(render(:partial => 'edit')).html_safe %>");
$('#edit_user').dialog('open');

app/views/users/index.html.erb
<input type="BUTTON" id="add_button" value="Add User" />
<input type="BUTTON" id="edit_button" value="Edit Selected" />
<input type="BUTTON" id="role_button" value="Add/Edit Role" />
<br />
<table id=users_list width="100%">
</table>
<div id=users_pager></div>

<% content_for :head do %>
  <%= raw(users_jqgrid) %>
<% end %>



<table id="editgrid"></table> 
<div id="pagered"></div> 

app/views/users/new.js.erb
$('#add_user').html ("<%= escape_javascript(render(:partial => 'new')).html_safe %>");
$('#add_user').dialog('open');

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.user_name %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Roles:</b>
  <%= @user.roles.map(&:name).join(",")%>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back to GridView', users_path %>

app/views/users/update.js.erb
$('#edit_user').dialog('close');
$('#users_list').trigger('reloadGrid');